- type: job
  parent: RMCJobRibbonBase
  id: AU14JobCivilianColonist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianColonist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillDomestics: 1
  - type: JobPrefix
    prefix: au14-job-prefix-civiliancolonist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14colonyjobicons.rsi
      state: colonist

  name: au14-job-name-civiliancolonist
  description: au14-job-description-civiliancolonist
  setPreference: true
  playTimeTracker: AU14JobCivilianColonist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianColonist
  icon: "AU14JobIconColonyColonist"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: cmu-spawn-role-colonist-cmu
  accessGroups:
  - Colonist
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianColonist
  equipment:
    jumpsuit: CMJumpsuitColonist
    shoes: RMCShoesBlack
    id: AU14IDCardColonyColonist

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianColonist
  name: Spawn Point Civilian Colonist
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonist
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianColonist
  isHumanoid: true

# ├──[ colony ]──────────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobCivilianColonist
  points: 20
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - AU14ColonistPerkGroupFirearms
  - AU14ColonistPerkGroupMelee
  - AU14ColonistPerkGroupEngineering
  - AU14ColonistPerkGroupMedical
  - AU14ColonistPerkGroupDriving
  - AU14ColonistPerkGroupCooking
